[package]
name = "neophoebe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# GSL = "6.0.0"
rand = "0.8.5"
itertools = "0.10.5"
ron = "0.8.0"
serde = { version = "1.0.164", features = ["derive"] }